package chunk

import "strings"

// EmbedText is what's actually sent to the embedding endpoint. Stamping
// path + kind + name + parent into the embedded text improves retrieval
// for both top-level and nested declarations.
func (c Chunk) EmbedText() string {
	var b strings.Builder
	b.WriteString("// path: ")
	b.WriteString(c.Path)
	b.WriteByte('\n')
	if c.Kind != "" && c.Kind != KindWindow {
		b.WriteString("// kind: ")
		b.WriteString(c.Kind)
		b.WriteByte('\n')
	}
	if c.Parent != "" {
		b.WriteString("// parent: ")
		b.WriteString(c.Parent)
		b.WriteByte('\n')
	}
	if c.Name != "" {
		b.WriteString("// name: ")
		b.WriteString(c.Name)
		b.WriteByte('\n')
	}
	b.WriteString(c.Content)
	return b.String()
}

// EmbedTextWithContext prepends a one-sentence situating summary to the
// standard EmbedText output. The sentence is generated by the drain
// pipeline (chunk_context kind) and stored in chunks.context_text.
// When contextSentence is empty, EmbedText() is returned unchanged.
func (c Chunk) EmbedTextWithContext(contextSentence string) string {
	if contextSentence == "" {
		return c.EmbedText()
	}
	return "// context: " + contextSentence + "\n" + c.EmbedText()
}
