// `dex config` — manage per-project .dex/config.yml.
//
//	dex config init           scaffold .dex/config.yml if not present
//	dex config init --force   overwrite existing
//	dex config init --full    include all tuning knobs (commented out)
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func cmdConfig(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("config needs a subcommand: init")
	}
	sub, rest := args[0], args[1:]
	switch sub {
	case "init":
		return cmdConfigInit(rest)
	case "-h", "--help", "help":
		fmt.Fprintln(os.Stderr, `usage:
  dex config init [--force] [--full]   scaffold .dex/config.yml with commented defaults`)
		return nil
	default:
		return fmt.Errorf("unknown config subcommand: %s (have: init)", sub)
	}
}

func cmdConfigInit(args []string) error {
	fs := flag.NewFlagSet("config init", flag.ContinueOnError)
	setHelp(fs,
		"Scaffold .dex/config.yml with commented defaults from the current effective config.",
		"dex config init [--force] [--full]",
		"dex config init           # create .dex/config.yml if not present",
		"dex config init --force   # overwrite existing",
		"dex config init --full    # include all tuning knobs",
	)
	force := fs.Bool("force", false, "overwrite existing .dex/config.yml")
	full := fs.Bool("full", false, "include all tuning knobs (commented out)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() > 0 {
		return fmt.Errorf("config init takes no positional arguments")
	}

	wd, err := os.Getwd()
	if err != nil {
		return err
	}
	cfgDir := filepath.Join(wd, ".dex")
	cfgPath := filepath.Join(cfgDir, "config.yml")

	if _, err := os.Stat(cfgPath); err == nil && !*force {
		return fmt.Errorf("%s already exists — pass --force to overwrite", cfgPath)
	}

	body := buildConfigYAML(*full)

	if err := os.MkdirAll(cfgDir, 0o755); err != nil {
		return fmt.Errorf("create .dex/: %w", err)
	}
	if err := os.WriteFile(cfgPath, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", cfgPath, err)
	}
	fmt.Printf("wrote %s\n", cfgPath)
	fmt.Println("  edit endpoints/models to match your setup, then: dex doctor")
	return nil
}

// scaffoldConfigIfAbsent writes a starter .dex/config.yml under dir when none
// exists, so the indexer has an active include and `dex index .` works out of
// the box. Returns the config path and whether it was created. A pre-existing
// config is left untouched (created=false).
func scaffoldConfigIfAbsent(dir string) (string, bool, error) {
	cfgDir := filepath.Join(dir, ".dex")
	cfgPath := filepath.Join(cfgDir, "config.yml")
	if _, err := os.Stat(cfgPath); err == nil {
		return cfgPath, false, nil
	}
	if err := os.MkdirAll(cfgDir, 0o755); err != nil {
		return cfgPath, false, fmt.Errorf("create .dex/: %w", err)
	}
	if err := os.WriteFile(cfgPath, []byte(buildConfigYAML(false)), 0o644); err != nil {
		return cfgPath, false, fmt.Errorf("write %s: %w", cfgPath, err)
	}
	return cfgPath, true, nil
}

// buildConfigYAML generates the .dex/config.yml starter file.
// When full=true, includes the tuning section with all knobs commented out.
func buildConfigYAML(full bool) string {
	// Read current effective values so the generated file is pre-filled.
	resolved := resolveEnv(allEnvVars)
	byName := make(map[string]effVar, len(resolved))
	for _, v := range resolved {
		byName[v.Name] = v
	}

	eff := func(name string) string {
		if v, ok := byName[name]; ok && v.Value != "" && v.Source != "default" {
			return v.Value
		}
		return ""
	}
	effOrDefault := func(name, fallback string) string {
		if v := eff(name); v != "" {
			return v
		}
		return fallback
	}

	var b strings.Builder
	writeln := func(s string) { b.WriteString(s + "\n") }

	writeln("# .dex/config.yml — dex per-project configuration")
	writeln("# Generated by `dex config init`. Run `dex env --doc` for all available knobs.")
	writeln("# Env vars always take precedence over values in this file.")
	writeln("")

	// endpoints section
	writeln("endpoints:")
	writeln("  # embed: OpenAI-compatible /v1/embeddings base URL  (DEX_EMBED_URL)")
	writeln("  embed: " + effOrDefault("DEX_EMBED_URL", "http://127.0.0.1:11434"))
	writeln("  # chat: OpenAI-compatible /v1/chat/completions URL  (DEX_CHAT_URL)")
	writeln("  chat:  " + effOrDefault("DEX_CHAT_URL", "http://127.0.0.1:11434"))
	writeln("")

	// models section
	writeln("models:")
	writeln("  # embed: model name for embedding  (DEX_EMBED_MODEL)")
	writeln("  embed: " + effOrDefault("DEX_EMBED_MODEL", "nomic-embed-text"))
	writeln("  # chat: model name for ask/generate/read summary  (DEX_CHAT_MODEL)")
	writeln("  chat:  " + effOrDefault("DEX_CHAT_MODEL", "qwen2.5-coder:14b"))
	writeln("")

	// index section — active by default so `dex index .` works out of the box.
	// include is required (nothing is indexed without it); default to the
	// project root and let the user scope it down. .gitignore is always honored.
	writeln("# index: control which files are indexed (include is required)")
	writeln("index:")
	writeln("  include:")
	writeln("    - \"**\"           # index the whole tree (edit to scope, e.g. cmd/, internal/)")
	writeln("  # ignore:          # additional paths to skip (on top of .gitignore)")
	writeln("  #   - vendor")
	writeln("")

	// Optional rerank (off by default)
	writeln("# rerank: optional cross-encoder endpoint for improved ranking")
	writeln("# endpoints:")
	writeln("#   rerank: http://127.0.0.1:8084   # DEX_RERANK_URL")
	writeln("# models:")
	writeln("#   rerank: Qwen/Qwen3-Reranker-4B   # DEX_RERANK_MODEL")
	writeln("")

	// tools section
	writeln("# tools:")
	writeln("")

	if full {
		writeln("# ── tuning knobs (all optional) ─────────────────────────────────────────────────")
		writeln("")
		writeln("# env: escape hatch — set any DEX_* knob directly")
		writeln("# env:")
		writeln("#   DEX_EMBED_BATCH:        auto    # chunks per /v1/embeddings call (auto: 16 ollama, else VRAM-sized)")
		writeln("#   DEX_EMBED_CONCURRENCY:  auto    # parallel embed calls (auto: 4 ollama, 1 true-batching server)")
		writeln("#   DEX_EMBED_TIMEOUT:        60s   # HTTP timeout per embed call")
		writeln("#   DEX_INDEX_CONCURRENCY:     0    # parallel file readers (0=GOMAXPROCS)")
		writeln("#   DEX_RERANK_POOL:          40    # candidates fed to the reranker")
		writeln("#   DEX_RERANK_STYLE:     chat-vllm # cohere | chat | chat-vllm")
		writeln("#   DEX_MAX_HITS_PER_FILE:     0    # cap hits per file (0=no cap)")
		writeln("#   DEX_MCP_AUTOWATCH:         1    # 0 to disable MCP auto-watcher")
		writeln("#   DEX_WATCH_DEBOUNCE:      500ms  # quiet window for MCP auto-watcher")
	}

	return b.String()
}
